import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const configPath = path.join(__dirname, '../config/ports.json');
const envPath = path.join(__dirname, '../.env');

function loadConfig() {
  try {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    return config;
  } catch (error) {
    console.error('Error loading port config:', error);
    return null;
  }
}

async function findAvailablePort(startPort, maxAttempts = 10) {
  const net = await import('net');
  
  return new Promise((resolve, reject) => {
    let port = startPort;
    let attempts = 0;
    
    function tryPort() {
      if (attempts >= maxAttempts) {
        reject(new Error(`Could not find available port starting from ${startPort}`));
        return;
      }
      
      const server = net.default.createServer();
      
      server.listen(port, () => {
        server.close(() => {
          resolve(port);
        });
      });
      
      server.on('error', (err) => {
        if (err.code === 'EADDRINUSE') {
          port++;
          attempts++;
          tryPort();
        } else {
          reject(err);
        }
      });
    }
    
    tryPort();
  });
}

async function setupPorts() {
  const config = loadConfig();
  if (!config) return;
  
  const environment = process.env.NODE_ENV || 'development';
  const envConfig = config[environment];
  
  if (!envConfig) {
    console.error(`No configuration found for environment: ${environment}`);
    return;
  }
  
  try {
    // Find available backend port
    const backendPort = await findAvailablePort(envConfig.backend);
    
    // Find available frontend port
    const frontendPort = await findAvailablePort(envConfig.frontend);
    
    // Update environment variables
    const envContent = `# Auto-generated by port-manager
VITE_API_URL=http://localhost:${backendPort}
SERVER_PORT=${backendPort}
FRONTEND_PORT=${frontendPort}

# Database Configuration
DATABASE_URL=postgresql://postgres:bagheri13@localhost:5432/growladder
`;
    
    fs.writeFileSync(envPath, envContent);
    
    console.log(`✅ Ports configured successfully:`);
    console.log(`   Frontend: ${frontendPort}`);
    console.log(`   Backend: ${backendPort}`);
    console.log(`   API URL: http://localhost:${backendPort}`);
    
    return { frontendPort, backendPort };
  } catch (error) {
    console.error('Error setting up ports:', error);
    process.exit(1);
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  setupPorts();
}

export { setupPorts, findAvailablePort };
